version: "3"
services:
    user-service:
        build: ./
        volumes:
            - ./src:/app/src
        container_name: user-service
        restart: always
        environment:
            - PORT=8080
        #    - DATABASE_URL=postgres://postgres:root@psql-container:5432/postgres
            - DATABASE_URL=postgres://postgres:postgres@psql-container:5432/postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            - my-net
        ports:
            - 8080:8080
        depends_on:
            - psql-container
        command: npm run dev
    psql-container:
        image: postgres
        container_name: psql-container
        environment:
        #    - DATABASE_PORT=5000
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./sql/Inicializar_base.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 5432:5432
        networks:
            - my-net
networks:
    my-net:
        driver: bridge
