version: "3"
services:
    user-service:
        build: ./
        volumes:
            - ./src:/app/src
        container_name: user-service
        restart: always
        environment:
            - PORT=8080
        #    - DATABASE_URL=postgres://postgres:root@psql-container:5432/postgres
            - DATABASE_URL=postgres://postgres:postgres@psql-container:5432/postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            - my-net
        ports:
            - ${PORT}:${PORT}
            - 8000:8000
        #command:
        #    - npm run dev
        depends_on:
            - psql-container
    psql-container:
        image: postgres
        container_name: psql-container
        environment:
        #    - DATABASE_PORT=5000
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./sql/Inicializar_base.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - my-net
        #command: postgres -p ${DATABASE_PORT}
        
networks:
    my-net:
        driver: bridge
