version: "3"
services:
    user-service:
        build: ./
        volumes:
            - ./src:/app/src
        container_name: user-service
        restart: always
        env_file:
            - .env
        networks:
            - my-net
        depends_on:
            - psql-users
    psql-users:
        image: postgres
        container_name: psql-users
        environment:
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./sql/Inicializar_base.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - my-net
networks:
  my-net:
    external:
      name: my-net

