version: "3"
services:
    user-service:
        build: ./
        volumes:
            - ./src:/app/src
        container_name: user-service
        restart: always
        env_file:
            - .env
        networks:
            - my-net
            - user-net
        ports:
            - ${PORT}:${PORT}
        depends_on:
            - psql-users
        command: npm run dev
    psql-users:
        image: postgres
        container_name: psql-users
        environment:
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./sql/Inicializar_base.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 5430:5432
        networks:
            - user-net
            
networks:
    my-net:
        driver: bridge
        name: my-net
    user-net:
        driver: bridge
        name: user-net
